### PR TITLE
Implemented look into archive files (#26)

### PR DESCRIPTION
**Pull request by viktor-podzigun**
In this PR was implemented look into archive files feature #26, using libarchive library on Linux and OS X.
Windows is not supported currently, since there is no precompiled DLL libraries, and I have no experience with compiling Linux libs for Windows. I suggest opening separate issue for support windows platform for this feature.

### CODE REVIEW

**Comment by corporateshark** [comment]
CMake builds failed: https://travis-ci.org/corporateshark/WCMCommander/builds/82903163

**Comment by viktor-podzigun** [comment]
CMake build failed because it didn't found libarchaive:
```bash
CMake Error at src/CMakeLists.txt:65 (MESSAGE):
  LibArchive not found.  You should either install it or disable
  WITH_LIBARCHIVE cmake option
```

**Comment by corporateshark** [comment]
Should be disabled by default then.

**Comment by viktor-podzigun** [comment]
Thanks!

**Pull request merged**
