### PR TITLE
Enabled smbclient lib

### PR DESCRIPTION
**Pull request by viktor-podzigun**
Are you OK to enable smbclient lib also? I've just tested it on OS X works fine for me.

BTW, installed it using: brew install samba

### CODE REVIEW

**Comment by corporateshark** [comment]
Sure, it is ok. How about Windows?

**Comment by viktor-podzigun** [comment]
Didn't think about it :D It seems native for Windows.

Will investigate if there is a way to compile it under win, same as done for libssh2. Or we can disable it for Windows by now.

**Comment by corporateshark** [comment]
Let's disable it for Windows.

**Comment by viktor-podzigun** [comment]
Would be great! Could you, please, advice how to do it? (Since I'm not so advanced with cmake.)

**Comment by corporateshark** [comment]
VisualStudio can be detected in CMake with this snippet:

``if (MSVC)``
``endif(MSVC``

There should be a similar way for MinGW.

**Comment by viktor-podzigun** [comment]
Thanks @corporateshark for your help.

**Comment by corporateshark** [comment]
No problem.

**Pull request merged**
