### PR TITLE
change icon to FAR like, add ROOT WCM mode and special icon

### PR DESCRIPTION
**Pull request by belonesox**
I propose using FAR-like icons (with colors from WCM default style)
(SVG-sources of these icons can be found at https://abf.io/import/wcmcommander )

Normal "blue" FAR-like icon for regular WCM mode, and special "red" icon for "root mode", when WCM  is launched by root (kdesu, gksu, etc...).

BTW, I can not understand why in GNOME Shell, in ALT-TAB mode always used this 32x32 XPM Icons, and ignore SVG icons from icon theme...

### CODE REVIEW

**Comment by corporateshark** [comment]
There is a function ``IsRoot()``.

**Comment by belonesox** [comment]
I am not sure about workflow here.

I have to use "IsRoot()" and rerequest new patch?
Or you can fix it?

Is any other problems with this merge?

**Comment by corporateshark** [comment]
Yes, make it the right way.

**Comment by belonesox** [comment]
Sorry for delay…

**Comment by belonesox** [comment]
Increase resolution of raster WCM icons to 64x64

**Comment by corporateshark** [comment]
Can you make a ``.ico`` file for Windows using these images?

**Comment by belonesox** [comment]
Can you make a .ico file for Windows using these images?

Probably yes, 
    convert wcmcommander.svg   -resize 64x64  wcm.ico 

→ https://cloud.mail.ru/public/LMUY/6cFh35dYu

I have to commit SVG and ICO? 
I  am not sure, where them should be placed in the source tree.

**Comment by corporateshark** [comment]
Just replace the ``.ico`` file in the repository to use the same icon on all platforms.

**Comment by belonesox** [comment]
Hm. I am on linux now, I can not check that .ico will be OK on Windows.
And where to place SVG source files?

**Comment by corporateshark** [comment]
Please, put it into ``docs``.

Sure, I will test the complete pull-request.

**Comment by belonesox** [comment]
replace ico and add SVG-sources of icon

**Comment by corporateshark** [comment]
Great job. Thank you.

**Comment by viktor-podzigun** [comment]
Looks really nice (attached my screenshots from OS X). Thanks @belonesox
cmd_tab
dock

**Pull request merged**
